# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-passwd-creator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(498, 344)
        Form.setStyleSheet("background:qlineargradient(spread:pad, x1:0.59, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(169, 163, 163, 255));\n"
"\n"
"")
        self.create = QtWidgets.QPushButton(Form)
        self.create.setGeometry(QtCore.QRect(30, 30, 75, 31))
        self.create.setStyleSheet("border:1px solid #000;border-radius:5px;color:purple;background-color:rgb(191, 191, 191);\n"
"\n"
"")
        self.create.setObjectName("create")
        self.get_value = QtWidgets.QTextEdit(Form)
        self.get_value.setGeometry(QtCore.QRect(150, 30, 290, 30))
        self.get_value.setStyleSheet("border:1px solid;background-color:#fff;")
        self.get_value.setObjectName("get_value")
        self.Label_output = QtWidgets.QLabel(Form)
        self.Label_output.setGeometry(QtCore.QRect(10, 200, 111, 51))
        self.Label_output.setStyleSheet("color:#fff;border-radius:25px;border:1px solid white;\n"
"\n"
"")
        self.Label_output.setObjectName("Label_output")
        self.OutPut = QtWidgets.QTextBrowser(Form)
        self.OutPut.setGeometry(QtCore.QRect(10, 260, 481, 81))
        self.OutPut.setStyleSheet("background-color:#fff;border:1px solid #000")
        self.OutPut.setObjectName("OutPut")
        self.Reset = QtWidgets.QPushButton(Form)
        self.Reset.setGeometry(QtCore.QRect(410, 150, 75, 23))
        self.Reset.setStyleSheet("background-color:rgb(141, 141, 141);border:1px solid #000;border-radius:4px;\n"
"color:white;\n"
"")
        self.Reset.setObjectName("Reset")

        self.retranslateUi(Form)
        self.create.clicked.connect(self.get_value.selectAll)
        self.create.clicked.connect(self.OutPut.update)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create.setText(_translate("Form", "Create"))
        self.get_value.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Label_output.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">OutPut:</span></p></body></html>"))
        self.OutPut.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Reset.setText(_translate("Form", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
